// X-Power 电池产品数据
// 所有图片路径使用上传后的存储路径

export interface BatterySpec {
  model: string;
  voltage: string;
  energy: string;
  humidity: string;
  motorPower: string;
  chargeTemp: string;
  dischargeTemp: string;
  maxChargeCurrent: string;
  maxDischargeCurrent: string;
  maxChargeVoltage: string;
  minDischargeVoltage: string;
  storageTemp: string;
  storageSOC: string;
  dimensions: string;
  application: string[];
  image: string;
}

export interface BatterySeries {
  id: string;
  seriesKey: string;
  voltage: string;
  products: BatterySpec[];
}

export const batterySeries: BatterySeries[] = [
  {
    id: '52v',
    seriesKey: 'series.52v',
    voltage: '52V',
    products: [
      {
        model: '5230-FB',
        voltage: '52V',
        energy: '1536Wh',
        humidity: '≤85%RH',
        motorPower: '≤1200W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '10A',
        maxDischargeCurrent: '50A',
        maxChargeVoltage: '58.4V',
        minDischargeVoltage: '40V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '180×151×280mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/5230-FB-new_82485c7a.png',
      },
      {
        model: '5240-FE',
        voltage: '52V',
        energy: '1920Wh',
        humidity: '≤85%RH',
        motorPower: '≤1500W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '12A',
        maxDischargeCurrent: '50A',
        maxChargeVoltage: '58.8V',
        minDischargeVoltage: '40V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '180×160×310mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/5240-FE-new_6327868f.jpg',
      },
      {
        model: '5252-FB',
        voltage: '51.2V',
        energy: '2662Wh',
        humidity: '≤85%RH',
        motorPower: '≤1500W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '20A',
        maxDischargeCurrent: '50A',
        maxChargeVoltage: '58.4V',
        minDischargeVoltage: '40V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '208×148×210mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/5252-FB_f0883775.png',
      },
      {
        model: '5260-FE',
        voltage: '52V',
        energy: '2880Wh',
        humidity: '≤85%RH',
        motorPower: '≤1500W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '20A',
        maxDischargeCurrent: '50A',
        maxChargeVoltage: '58.8V',
        minDischargeVoltage: '40V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '190×168×345mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/5260-FE_8ffd7150.png',
      },
      {
        model: '5275-FE',
        voltage: '52V',
        energy: '3600Wh',
        humidity: '≤85%RH',
        motorPower: '≤2000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '25A',
        maxDischargeCurrent: '16A',
        maxChargeVoltage: '58.8V',
        minDischargeVoltage: '40V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '190×160×345mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/5275-FE_79d45095.png',
      },
    ],
  },
  {
    id: '60v',
    seriesKey: 'series.60v',
    voltage: '60V',
    products: [
      {
        model: '6422-FB',
        voltage: '64V',
        energy: '1280Wh',
        humidity: '≤85%RH',
        motorPower: '≤1200W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '6A',
        maxDischargeCurrent: '35A',
        maxChargeVoltage: '73V',
        minDischargeVoltage: '50V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '315×180×163mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/6422-FB_85c20884.png',
      },
      {
        model: '6430-FB',
        voltage: '64V',
        energy: '1600Wh',
        humidity: '≤85%RH',
        motorPower: '≤1500W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '10A',
        maxDischargeCurrent: '50A',
        maxChargeVoltage: '73V',
        minDischargeVoltage: '50V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '322×202×163mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/6430-FB_17fcb23d.png',
      },
      {
        model: '6040-FE',
        voltage: '60V',
        energy: '2400Wh',
        humidity: '≤85%RH',
        motorPower: '≤2000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '12A',
        maxDischargeCurrent: '60A',
        maxChargeVoltage: '71.4V',
        minDischargeVoltage: '50V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '180×155×325mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/6040-FE_fa12a33f.png',
      },
      {
        model: '6445-FB',
        voltage: '64V',
        energy: '2880Wh',
        humidity: '≤85%RH',
        motorPower: '≤2000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '11A',
        maxDischargeCurrent: '60A',
        maxChargeVoltage: '73V',
        minDischargeVoltage: '50V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '322×180×332mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/6445-FB_6e7c179a.png',
      },
      {
        model: '6455-FB',
        voltage: '64V',
        energy: '3200Wh',
        humidity: '≤80%RH',
        motorPower: '≤2500W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '20A',
        maxDischargeCurrent: '80A',
        maxChargeVoltage: '73V',
        minDischargeVoltage: '50V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '470×220×166mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/6455-FB_e6b94438.png',
      },
      {
        model: '6060-FE',
        voltage: '60V',
        energy: '3450Wh',
        humidity: '≤85%RH',
        motorPower: '≤2000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '25A',
        maxDischargeCurrent: '80A',
        maxChargeVoltage: '71.4V',
        minDischargeVoltage: '50V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '222×160×347mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/6060-FE_138daa09.png',
      },
    ],
  },
  {
    id: '72v',
    seriesKey: 'series.72v',
    voltage: '72V',
    products: [
      {
        model: '6075-FE',
        voltage: '60V',
        energy: '4500Wh',
        humidity: '≤85%RH',
        motorPower: '≤2500W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '25A',
        maxDischargeCurrent: '80A',
        maxChargeVoltage: '71.4V',
        minDischargeVoltage: '50V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '222×182×347mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/6075-FE_b97a005a.png',
      },
      {
        model: '7622-FB',
        voltage: '76.8V',
        energy: '1536Wh',
        humidity: '≤85%RH',
        motorPower: '≤1200W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '6A',
        maxDischargeCurrent: '35A',
        maxChargeVoltage: '87.4V',
        minDischargeVoltage: '60V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '315×180×163mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/7622-FB_bb69fb8a.png',
      },
      {
        model: '7630-FB',
        voltage: '72V',
        energy: '1920Wh',
        humidity: '≤85%RH',
        motorPower: '≤2000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '10A',
        maxDischargeCurrent: '30A',
        maxChargeVoltage: '87.4V',
        minDischargeVoltage: '60V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '374×203×163mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/7630-FB_caf6ed94.png',
      },
      {
        model: '7240-FE',
        voltage: '72V',
        energy: '2880Wh',
        humidity: '≤85%RH',
        motorPower: '≤2000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '10A',
        maxDischargeCurrent: '50A',
        maxChargeVoltage: '87.4V',
        minDischargeVoltage: '60V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '222×182×347mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/7240-FE_3253d1f6.png',
      },
      {
        model: '7645-FB',
        voltage: '76.8V',
        energy: '3226Wh',
        humidity: '≤85%RH',
        motorPower: '≤2500W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '15A',
        maxDischargeCurrent: '40A',
        maxChargeVoltage: '87.4V',
        minDischargeVoltage: '60V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '220×180×352mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/7645-FB_861b1506.png',
      },
      {
        model: '7655-FB',
        voltage: '76.8V',
        energy: '3840Wh',
        humidity: '≤85%RH',
        motorPower: '≤3000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '12A',
        maxDischargeCurrent: '80A',
        maxChargeVoltage: '84V',
        minDischargeVoltage: '60V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '472×135×163mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/7655-FB_b9a6ca65.png',
      },
      {
        model: '7260-FE',
        voltage: '72V',
        energy: '4320Wh',
        humidity: '≤85%RH',
        motorPower: '≤3000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '15A',
        maxDischargeCurrent: '60A',
        maxChargeVoltage: '84V',
        minDischargeVoltage: '60V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '222×180×347mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/7260-FE_4d2f6371.png',
      },
      {
        model: '7275-FE',
        voltage: '72V',
        energy: '5400Wh',
        humidity: '≤85%RH',
        motorPower: '≤3000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '25A',
        maxDischargeCurrent: '80A',
        maxChargeVoltage: '84V',
        minDischargeVoltage: '60V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '222×182×347mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/7275-FE_32080250.png',
      },
      {
        model: '7691-FB',
        voltage: '76.8V',
        energy: '6989Wh',
        humidity: '≤85%RH',
        motorPower: '≤3000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '30A',
        maxDischargeCurrent: '120A',
        maxChargeVoltage: '84V',
        minDischargeVoltage: '60V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '567×286×175mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/7691-FB_1e795ebe.png',
      },
      {
        model: '72113-FE',
        voltage: '72V',
        energy: '8136Wh',
        humidity: '≤85%RH',
        motorPower: '≤6000W',
        chargeTemp: '-20°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '50A',
        maxDischargeCurrent: '120A',
        maxChargeVoltage: '84V',
        minDischargeVoltage: '60V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '487×227×175mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/72113-FE_3703408b.png',
      },
      {
        model: '72141-FE',
        voltage: '72V',
        energy: '10152Wh',
        humidity: '≤85%RH',
        motorPower: '≤6000W',
        chargeTemp: '-20°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '70A',
        maxDischargeCurrent: '150A',
        maxChargeVoltage: '84V',
        minDischargeVoltage: '60V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '572×260×170mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/72141-FE_3ec0ac10.png',
      },
    ],
  },
  {
    id: '64v',
    seriesKey: 'series.64v',
    voltage: '64V',
    products: [
      {
        model: '6455-FB',
        voltage: '64V',
        energy: '3200Wh',
        humidity: '≤80%RH',
        motorPower: '≤2500W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '20A',
        maxDischargeCurrent: '80A',
        maxChargeVoltage: '73V',
        minDischargeVoltage: '50V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '410×235×166mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/6455-FB-64V_0899ea71.png',
      },
      {
        model: '6470-FB',
        voltage: '64V',
        energy: '3840Wh',
        humidity: '≤80%RH',
        motorPower: '≤3000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '20A',
        maxDischargeCurrent: '80A',
        maxChargeVoltage: '73V',
        minDischargeVoltage: '50V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '620×261×148mm',
        application: ['app.threewheeler', 'app.fourwheeler', 'app.cleaning'],
        image: '/manus-storage/6470-FB_a62edb87.png',
      },
      {
        model: '64110-FB',
        voltage: '64V',
        energy: '6080Wh',
        humidity: '≤80%RH',
        motorPower: '≤3000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '30A',
        maxDischargeCurrent: '120A',
        maxChargeVoltage: '73V',
        minDischargeVoltage: '50V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '532×313×194mm',
        application: ['app.threewheeler', 'app.fourwheeler', 'app.cleaning'],
        image: '/manus-storage/64110-FB_c66e65a5.png',
      },
      {
        model: '64150-FB',
        voltage: '64V',
        energy: '9280Wh',
        humidity: '≤80%RH',
        motorPower: '≤3000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '40A',
        maxDischargeCurrent: '120A',
        maxChargeVoltage: '73V',
        minDischargeVoltage: '50V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '577×357×248mm',
        application: ['app.threewheeler', 'app.fourwheeler', 'app.cleaning'],
        image: '/manus-storage/64150-FB_1c2b290f.png',
      },
      {
        model: '64200-FB',
        voltage: '64V',
        energy: '12160Wh',
        humidity: '≤80%RH',
        motorPower: '≤4000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '55A',
        maxDischargeCurrent: '150A',
        maxChargeVoltage: '73V',
        minDischargeVoltage: '50V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '665×393×268mm',
        application: ['app.threewheeler', 'app.fourwheeler', 'app.cleaning'],
        image: '/manus-storage/64200-FB_eed25177.png',
      },
      {
        model: '64300-FB',
        voltage: '64V',
        energy: '19200Wh',
        humidity: '≤80%RH',
        motorPower: '≤6000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '80A',
        maxDischargeCurrent: '150A',
        maxChargeVoltage: '73V',
        minDischargeVoltage: '50V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '800×513×248mm',
        application: ['app.threewheeler', 'app.fourwheeler', 'app.cleaning'],
        image: '/manus-storage/64300-FB_3b4d1d09.png',
      },
    ],
  },
  {
    id: '768v',
    seriesKey: 'series.768v',
    voltage: '76.8V',
    products: [
      {
        model: '7655-FB',
        voltage: '76.8V',
        energy: '3840Wh',
        humidity: '≤85%RH',
        motorPower: '≤3000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '12A',
        maxDischargeCurrent: '80A',
        maxChargeVoltage: '87.4V',
        minDischargeVoltage: '60V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '472×155×165mm',
        application: ['app.twowheeler', 'app.threewheeler'],
        image: '/manus-storage/7655-FB-768V_3bb387b6.png',
      },
      {
        model: '7670-FB',
        voltage: '76.8V',
        energy: '4608Wh',
        humidity: '≤85%RH',
        motorPower: '≤2500W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '20A',
        maxDischargeCurrent: '80A',
        maxChargeVoltage: '84V',
        minDischargeVoltage: '60V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '620×261×148mm',
        application: ['app.threewheeler', 'app.fourwheeler', 'app.cleaning'],
        image: '/manus-storage/7670-FB_dde2f570.png',
      },
      {
        model: '76110-FB',
        voltage: '76.8V',
        energy: '7296Wh',
        humidity: '≤80%RH',
        motorPower: '≤3000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '30A',
        maxDischargeCurrent: '120A',
        maxChargeVoltage: '87.4V',
        minDischargeVoltage: '60V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '532×313×220mm',
        application: ['app.threewheeler', 'app.fourwheeler', 'app.cleaning'],
        image: '/manus-storage/76110-FB_9d3789ea.png',
      },
      {
        model: '76150-FB',
        voltage: '76.8V',
        energy: '11136Wh',
        humidity: '≤85%RH',
        motorPower: '≤3000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '40A',
        maxDischargeCurrent: '120A',
        maxChargeVoltage: '87.4V',
        minDischargeVoltage: '60V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '672×377×248mm',
        application: ['app.threewheeler', 'app.fourwheeler', 'app.cleaning'],
        image: '/manus-storage/76150-FB_f456c631.png',
      },
      {
        model: '76200-FB',
        voltage: '76.8V',
        energy: '14592Wh',
        humidity: '≤80%RH',
        motorPower: '≤4000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '55A',
        maxDischargeCurrent: '150A',
        maxChargeVoltage: '87.4V',
        minDischargeVoltage: '60V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '700×381×248mm',
        application: ['app.threewheeler', 'app.fourwheeler', 'app.cleaning'],
        image: '/manus-storage/76200-FB_5f6fad5d.png',
      },
      {
        model: '76300-FB',
        voltage: '76.8V',
        energy: '23040Wh',
        humidity: '≤80%RH',
        motorPower: '≤4000W',
        chargeTemp: '0°C~45°C',
        dischargeTemp: '-20°C~55°C',
        maxChargeCurrent: '80A',
        maxDischargeCurrent: '150A',
        maxChargeVoltage: '87.4V',
        minDischargeVoltage: '60V',
        storageTemp: '0°C~35°C',
        storageSOC: '30%~70%',
        dimensions: '800×513×248mm',
        application: ['app.threewheeler', 'app.fourwheeler', 'app.cleaning'],
        image: '/manus-storage/76300-FB_da52137d.png',
      },
    ],
  },
];
